/* Generated by Cython 3.0.11 */

#ifndef __PYX_HAVE___gappedbuf
#define __PYX_HAVE___gappedbuf

#include "Python.h"
struct GappedBufferObj;

/* "_gappedbuf.pxd":2
 * 
 * cdef public class GappedBuffer [object GappedBufferObj, type GappedBufferType]:             # <<<<<<<<<<<<<<
 *     cdef public Py_ssize_t bufsize
 *     cdef public Py_ssize_t numelems
 */
struct GappedBufferObj {
  PyObject_HEAD
  struct __pyx_vtabstruct_10_gappedbuf_GappedBuffer *__pyx_vtab;
  Py_ssize_t bufsize;
  Py_ssize_t numelems;
  Py_ssize_t gap;
  Py_ssize_t gapsize;
  Py_UCS4 *buf;
};

#ifndef __PYX_HAVE_API___gappedbuf

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) GappedBufferType;

#endif /* !__PYX_HAVE_API___gappedbuf */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC init_gappedbuf(void);
#else
/* WARNING: Use PyImport_AppendInittab("_gappedbuf", PyInit__gappedbuf) instead of calling PyInit__gappedbuf directly from Python 3.5 */
PyMODINIT_FUNC PyInit__gappedbuf(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"_gappedbuf\", PyInit__gappedbuf) instead of calling PyInit__gappedbuf directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"_gappedbuf\", PyInit__gappedbuf) instead of calling PyInit__gappedbuf directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"_gappedbuf\", PyInit__gappedbuf) instead of calling PyInit__gappedbuf directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit__gappedbuf_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit__gappedbuf() __PYX_WARN_IF_PyInit__gappedbuf_INIT_CALLED(PyInit__gappedbuf())
#endif
#endif

#endif /* !__PYX_HAVE___gappedbuf */
